<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<AssemblyName>MakeVideo</AssemblyName>
		<RootNamespace>Pxoqxo.MakeVideo</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Assets\Images\favicon.ico" />
	  <None Remove="Assets\Images\favicon.jpg" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Assets\Images\favicon.ico" />
	  <Resource Include="Assets\Images\favicon.jpg" />
	</ItemGroup>

</Project>
